### ISSUE TITLE
sorry for disturbing you

### ISSUE THREAD

**Issue by r4vanan** [datajerk/ctf-write-ups#4]
i need some more clarification can you solve that please

**Comment by datajerk** [comment]
can you provide a link to the write up you are asking about?

**Comment by r4vanan** [comment]
https://github.com/datajerk/ctf-write-ups/tree/master/damctf2021/cookie-monster

**Comment by r4vanan** [comment]
i am a noob in pwn challenges so i am trying to learn on your repo so i need to how you deal with pwn challenges first .
sorry but i am curious to learn from you

**Comment by datajerk** [comment]
what questions did you have?

**Comment by r4vanan** [comment]
how you got this value %15$p

**Comment by datajerk** [comment]
i updated the writeup with more detail
