### ISSUE TITLE
when i run riscky's exp, it happens unbelievable thing,thank you

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeea** [datajerk/ctf-write-ups#5]
![1](https://user-images.githubusercontent.com/82768425/166402256-4fb57da0-5188-4671-8433-2c055b0667ed.png)

I don's know why.thank you!!

**Comment by eeeeeeeeeeeeeeeea** [comment]
i don's know how to add it system

**Comment by datajerk** [comment]
You do not need the system included headers.

Your setting for buf may be different from mine (depends on os version, env, etc...), so you'll have to use gdb to find a0 yourself.
